CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

CRUD/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/update/', views.update, name='update'),
]

CRUD/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=140)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

CRUD/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

def detail(request, article_pk):
    # article = Article.objects.get(id=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, article_pk):
    # article = Article.objects.get(id=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    article.delete()
    return redirect('articles:index')

def edit(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

CRUD/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block title %}
만들기
{% endblock %}
{% block body %}
{% endblock %}

CRUD/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %}
상세보기
{% endblock %}
{% block body %}
<h1>{{ article.id }}번 글</h1>
<p>제목: {{article.title}}</p>
<p>내용: {{article.content}}</p>
<p>최초 작성시간: {{article.created_at}}</p>
<p>최종 수정시간: {{article.updated_at}}</p>
<a href="{% url 'articles:delete' article.pk %}">삭제</a>
<a href="{% url 'articles:edit' article.pk %}">수정</a>
{% endblock %}

CRUD/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block title %}
수정
{% endblock %}
{% block body %}
<form action="{% url 'articles:update' article.pk %}" method = "POST">
  {% csrf_token %}
  제목: <input type="text" value="{{article.title}}" name="title">
  내용: <input type="text" value="{{article.content}}" name="content">
  <input type="submit" value="완료">
</form>
{% endblock %}

CRUD/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block title %}
목록 페이지
{% endblock %}

{% block body %}
<h2>목록</h2>
<a href="{% url 'articles:new' %}">글쓰기</a>
<hr>
{% for article in articles %}
<p>{{ article.id }}번 제목: {{ article.title }}</p>
<a href="{% url 'articles:detail' article.pk %}">자세히</a>
<hr>
{% endfor %}
{% endblock %}

CRUD/articles/templates/articles/new.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'stylesheets/form.css' %}">
{% endblock %}
{% block title %}
글쓰기
{% endblock %}
{% block body %}
<h1>글쓰기</h1>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  제목: <input type="text" name="title">
  내용: <textarea name="content" id="content"></textarea>
  <input type="submit" value="완료">
</form>
{% endblock %}