instagram/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail')
]

instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include

from articles import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

instagram/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

instagram/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

instagram/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.contrib import messages
# Create your views here.

def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            messages.success(request, '글 작성이 완료되었습니다.')
            return redirect('articles:detail', article.pk)
        messages.warning(request, '폼을 다시 확인 후 제출해주세요.')
    else:
        form = ArticleForm()
    context = {
        'form' : form
    }
    return render(request,'articles/forms.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

instagram/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block title %} {{ article.pk }}번 글 {% endblock %}

{% block body %}
<h1>{{ article.pk }}번 글</h1>
<p>제목: {{article.title}}</p>
<p>내용: {{article.content}}</p>
{% endblock %}

instagram/articles/templates/articles/forms.html
{% extends 'base.html' %}
{% block title %} New {% endblock %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button>확인</button>
  </form>
{% endblock %}

instagram/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block title %} Index {% endblock %}
{% block body %}
  <a href="{% url 'articles:create' %}">글쓰기</a>
  {% for article in articles %}
    <p>{{ article.pk }}</p>
    <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
  {% endfor %}
{% endblock %}

instagram/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Instagram - {% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  {% block css %}
  {% endblock %}
</head>
<body>
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
      <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  </div>
  {% endif %}
  <div class="container">
    {% block body %}
    {% endblock %}
    <hr>
    <a href="{% url 'articles:index' %}">목록</a>
  </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>